// Arquivo de letras offline gerado via LRCLIB
const repertorio = [
    {
        "artista": "Benito Di Paula",
        "titulo": "Retalhos de Cetim",
        "youtube": "#",
        "cifra": "#",
        "letra": "Ensaiei meu samba o ano inteiro\nComprei surdo e tamborim\nGastei tudo em fantasia\nEra só o que eu queria\nE ela jurou desfilar pra mim\n\nMinha escola estava tão bonita\nEra tudo o que eu queria ver\nEm retalhos de cetim\nEu dormi o ano inteiro\nE ela jurou desfilar pra mim\n\nMas chegou o carnaval\nE ela não desfilou\nEu chorei na avenida, eu chorei\nNão pensei que mentia a cabrocha\nQue eu tanto amei\n\nMinha escola estava tão bonita\nEra tudo o que eu queria ver\nEm retalhos de cetim\nEu dormi o ano inteiro\nE ela jurou desfilar pra mim\n\nMas chegou o carnaval\nE ela não desfilou\nEu chorei na avenida, eu chorei\nNão pensei que mentia a cabrocha\nQue eu tanto amei\n\nMas chegou o Carnaval\nE ela não desfilou\nEu chorei na avenida, eu chorei\nNão pensei que mentia a cabrocha\nQue eu tanto amei\n\nMas chegou o carnaval\nE ela não desfilou\nEu chorei na avenida, eu chorei"
    },
    {
        "artista": "Alcione",
        "titulo": "Não Deixe o Samba Morrer",
        "youtube": "#",
        "cifra": "#",
        "letra": "Não deixe o samba morrer\nNão deixe o samba acabar\nO morro foi feito de samba\nDe samba para gente sambar\n\nQuando eu não puder pisar mais na avenida\nQuando as minhas pernas não puderem aguentar\nLevar meu corpo junto com meu samba\nO meu anel de bamba\nEntrego a quem mereça usar\n\nQuando eu não puder pisar mais na avenida\nQuando as minhas pernas não puderem aguentar\nLevar meu corpo junto com meu samba\nO meu anel de bamba\nEntrego a quem mereça usar\n\nEu vou ficar\nNo meio do povo, espiando\nMinha escola perdendo ou ganhando\nMais um carnaval\n\nAntes de me despedir\nDeixo ao sambista mais novo\nO meu pedido final\nAntes de me despedir\nDeixo ao sambista mais novo\nO meu pedido final\n\nNão deixe o samba morrer\nNão deixe o samba acabar\nO morro foi feito de samba\nDe samba para gente sambar\n\nNão deixe o samba morrer\nNão deixe o samba acabar\nO morro foi feito de samba\nDe samba para gente sambar\n\nQuando eu não puder pisar mais na avenida\nQuando as minhas pernas não puderem aguentar\nLevar meu corpo junto com meu samba\nO meu anel de bamba\nEntrego a quem mereça usar\n\nQuando eu não puder pisar mais na avenida\nQuando as minhas pernas não puderem aguentar\nLevar meu corpo junto com meu samba\nO meu anel de bamba\nEntrego a quem mereça usar\n\nEu vou ficar\nNo meio do povo espiando\nMinha escola perdendo ou ganhando\nMais um carnaval\n\nAntes de me despedir\nDeixo ao sambista mais novo\nO meu pedido final\nAntes de me despedir\nDeixo ao sambista mais novo\nO meu pedido final\n\nNão deixe o samba morrer\nNão deixe o samba acabar\nO morro foi feito de samba\nDe samba para gente sambar\n\nNão deixe o samba morrer\nNão deixe o samba acabar\nO morro foi feito de samba\nDe samba para gente sambar\n\nNão deixe o samba morrer..."
    },
    {
        "artista": "Fundo de Quintal",
        "titulo": "O Show Tem Que Continuar",
        "youtube": "#",
        "cifra": "#",
        "letra": "Teu choro já não toca meu bandolim\nDiz que minha voz sufoca teu violão\nAfrouxaram-se as cordas e assim desafina\nQue pobre das rimas da nossa canção\nHoje somos folha morta\nMetais em surdina\nFechada a cortina Vazio o salão\n\nSe os duetos não se encontram mais\nE os solos perderam a emoção\nSe acabou o gás\nPra cantar o mais simples refrão\n\nSe a gente nota\nQue uma só nota\nJá nos esgota\nO show perde a razão\n\nMas iremos achar o tom\nUm acorde com lindo som\nE fazer com que fique bom\nOutra vez o nosso cantar\nE a gente vai ser feliz\nOlha nós outra vez no ar\nO show tem que continuar\n\nSe os duetos não se encontram mais\nE os solos perderam a emoção\nSe acabou o gás\nPra cantar o mais simples refrão\n\nSe a gente nota\nQue uma só nota Já nos esgota\nO show perde a razão\n\nMas iremos achar o tom\nUm acorde com lindo som\nE fazer com que fique bom\nO utra vez o nosso cantar\nE a gente vai ser feliz\nOlha nós outra vez no ar\nO show tem que continuar\n\nSe os duetos não se encontram mais\nE os solos perderam a emoção\nSe acabou o gás\nPra cantar o mais simples refrão\n\nSe a gente nota\nQue uma só nota Já nos esgota\nO show perde a razão\n\nNós iremos até Paris\nArrasar no Olímpia\nO show tem que continuar\n\nOlha o povo pedindo bis\nOs ingressos vão se esgotar\nO show tem que continuar\n\nNós iremos até Paris\nArrasar no Olímpia\nO show tem que continuar\n\nOlha o povo pedindo bis\nOs ingressos vão se esgotar\nO show tem que continuar\n\nTodo mundo que hoje diz\nAcabou vai se admirar\nNosso amor vai continuar\n\nLalaia lalaia laia\nLalaia lalaia laia...\n\nNosso amor vai continuar"
    },
    {
        "artista": "Zeca Pagodinho",
        "titulo": "Verdade",
        "youtube": "#",
        "cifra": "#",
        "letra": "Descobri que te amo demais\nDescobri em você minha paz\nDescobri sem querer a vida\nVerdade\n\nPra ganhar seu amor fiz mandinga\nFui a ginga de um bom capoeira\nDei rasteira na sua emoção\nCom o seu coração fiz zoeira\n\nFui a beira de um rio e você\nUma ceia com pãozinho e flor\nUma luz para guiar sua estrada\nA entrega perfeita do amor\nVerdade\n\nDescobri que te amo demais\nDescobri em você minha paz\nDescobri sem querer a vida\nVerdade\n\nComo negar essa linda emoção\nQue tanto bem fez pro meu coração\nE a minha paixão adormecida\n\nMeu amor, meu amor incendeia\nNossa cama parece uma teia\nTeu olhar uma luz que clareia\nMeu caminho tão claro, lua cheia\n\nEu nem posso pensar te perder\nAi de mim desse amor terminar\nSem você minha felicidade\nMorreria de tanto penar\nVerdade\n\nDescobri que te amo demais\nDescobri em você minha paz\nDescobri sem querer a vida\nVerdade\n\nComo negar essa linda emoção\nQue tanto bem fez pro meu coração\nE a minha paixão adormecida\n\nPra ganhar seu amor fiz mandinga\nFui a ginga de um bom capoeira\nDei rasteira na sua emoção\nCom o seu coração fiz zoeira\n\nFui a beira de um rio e você\nUma ceia com pãozinho e flor\nUma luz para guiar sua estrada\nA entrega perfeita do amor\nVerdade\n\nDescobri que te amo demais\nDescobri em você minha paz\nDescobri sem querer a vida\nVerdade\n\nComo negar essa linda emoção\nQue tanto bem fez pro meu coração\nA minha paixão adormecida\nDescobri que te amo demais\nDescobri em você minha paz\nDescobri sem querer a vida\nVerdade\n\nComo negar essa linda emoção\nQue tanto bem fez pro meu coração\nA minha paixão adormecida\nDescobri que te amo demais"
    }
];